basePath: /api/v1
definitions:
  handlers.PaginatedPostResponse:
    type: object
  models.CreatePost:
    properties:
      content:
        maxLength: 400
        minLength: 3
        type: string
    required:
    - content
    type: object
  models.DeleteCode:
    properties:
      code:
        type: string
    required:
    - code
    type: object
  models.MessageResponse:
    properties:
      message:
        type: string
    type: object
  models.Post:
    properties:
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      updatedAt:
        type: string
      userId:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      role:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  models.UserLogin:
    properties:
      password:
        type: string
      username:
        maxLength: 10
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  models.UserSignup:
    properties:
      email:
        type: string
      first_name:
        maxLength: 100
        minLength: 3
        type: string
      last_name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        minLength: 8
        type: string
      username:
        maxLength: 10
        minLength: 3
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - username
    type: object
info:
  contact: {}
  description: Social media API
  title: go-social API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Logs in the specified user
      parameters:
      - description: User details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      summary: Sign in
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logs out the user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      - refreshCookieAuth: []
      summary: Log Out
      tags:
      - auth
  /auth/me:
    delete:
      consumes:
      - application/json
      description: Deletes the logged in users account
      parameters:
      - description: The code received
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.DeleteCode'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      summary: Delete the logged in users account
      tags:
      - auth
    get:
      consumes:
      - application/json
      description: Get the logged in users account details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      summary: Get the logged in users details
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refreshes the users session
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - refreshCookieAuth: []
      summary: Refresh token
      tags:
      - auth
  /auth/request-delete-account:
    post:
      consumes:
      - application/json
      description: Requests a delete code so the user can delete their account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      summary: Request Delete Code
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: This creates the account
      parameters:
      - description: User details
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UserSignup'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      summary: Create a an account
      tags:
      - auth
  /posts:
    get:
      consumes:
      - application/json
      description: This retrieves a list of posts for the logged in user
      parameters:
      - description: The cursor to continue the search from
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PaginatedPostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      summary: Get a list of posts for the logged in user
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: This creates a new post for the user
      parameters:
      - description: Post body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.CreatePost'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      summary: Create a post
      tags:
      - posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: This deletes the specified post for the user
      parameters:
      - description: The post id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      summary: Delete a post
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: This retrieves the specified post
      parameters:
      - description: The post id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Post'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      summary: Get a post
      tags:
      - posts
  /users/{id}/posts:
    get:
      consumes:
      - application/json
      description: This retrieves a list of posts for the specified user
      parameters:
      - description: The user id
        in: path
        name: id
        required: true
        type: string
      - description: The cursor to continue the search from
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PaginatedPostResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.MessageResponse'
      security:
      - cookieAuth: []
      summary: Get list of posts for a specific user
      tags:
      - posts
securityDefinitions:
  cookieAuth:
    in: cookie
    name: access_token
    type: apiKey
  refreshCookieAuth:
    in: cookie
    name: refresh_token
    type: apiKey
swagger: "2.0"
